[2024-04-17 14:16:33,537: ERROR/ForkPoolWorker-1] Task statements.Create_Report[daa1af8c-cdbb-45c6-93a4-438aef529daf] raised unexpected: RuntimeError('Working outside of application context.\n\nThis typically means that you attempted to use functionality that needed\nthe current application. To solve this, set up an application context\nwith app.app_context(). See the documentation for more information.')
Traceback (most recent call last):
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/statements.py", line 226, in Create_Report
    db.session.add(data_object)
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 378, in add
    return self._proxied.add(instance, _warn=_warn)
           ^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/sqlalchemy/orm/scoping.py", line 197, in _proxied
    return self.registry()
           ^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/sqlalchemy/util/_collections.py", line 632, in __call__
    key = self.scopefunc()
          ^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/flask_sqlalchemy/session.py", line 111, in _app_ctx_id
    return id(app_ctx._get_current_object())  # type: ignore[attr-defined]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/werkzeug/local.py", line 508, in _get_current_object
    raise RuntimeError(unbound_message) from None
RuntimeError: Working outside of application context.

This typically means that you attempted to use functionality that needed
the current application. To solve this, set up an application context
with app.app_context(). See the documentation for more information.



















[2024-04-17 14:18:54,583: ERROR/ForkPoolWorker-1] Task statements.Create_Report[ca30bfe1-a27d-4029-ba9c-548925454efa] raised unexpected: RuntimeError("Unable to build URLs outside an active request without 'SERVER_NAME' configured. Also configure 'APPLICATION_ROOT' and 'PREFERRED_URL_SCHEME' as needed.")
Traceback (most recent call last):
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/statements.py", line 243, in Create_Report
    return render_template("report.html",
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/acidos/AISpy/application/templates/report.html", line 1, in top-level template code
    {% block head %}
  File "/home/acidos/AISpy/application/templates/report.html", line 2, in block 'head'
    {% include "_head.html"%}
  File "/home/acidos/AISpy/application/templates/_head.html", line 9, in top-level template code
    <link href="{{url_for('static', filename = 'css/bootstrap/bootstrap.min.css')}}" rel="stylesheet">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/acidos/AISpy/application/venv/lib/python3.11/site-packages/flask/app.py", line 1666, in url_for
    raise RuntimeError(
RuntimeError: Unable to build URLs outside an active request without 'SERVER_NAME' configured. Also configure 'APPLICATION_ROOT' and 'PREFERRED_URL_SCHEME' as needed.